#pragma config(Sensor, S1,     leftS,         sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     rightS,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     reflect,        sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motorD,           ,             tmotorEV3_Large, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "RobotLibrary.h"

void linetracking(){
	if((getColorName(S1) == colorRed) || (getColorName(S2) == colorRed)){
		STP();
	}
	if((getColorName(S1) == colorGreen) && (getColorName(S2) == colorGreen)){
			uturn();
	}
	else if ((getColorName(S1)==colorGreen)&&(getColorName(S2)!=colorGreen)){
			moveCM(lineWidthCM);
			sleep(1000);
			leftPointTurn();
	}
	else if ((getColorName(S1)!=colorGreen)&&(getColorName(S2)==colorGreen)){
			moveCM(lineWidthCM);
			sleep(1000);
			rightPointTurn();
	}
	if((getColorName(S1) == colorBlack) && (getColorName(S2) == colorBlack)){
		STP();
	}
	if((getColorName(S1) == colorWhite) && (getColorName(S2) == colorWhite)){
		forwards();
	}

}

/*void avoidObstacle(){

}*/

void setProperties(){ //change properties here instead of headerfile
setUTurn(340);
setSpeed(15);
setTurnSpeed(15);
setTurnValue(70);
setWheelDiamter(7.4);
}

task main(){
setProperties();
sleep(200);
forwards();
sleep(1500);
STP();
	repeat(forever){
		linetracking();
	}

}
